
export const districts = [
  {
    oid: 1,
    description: "Chilanga",
    districtCode: "No",
    provinceId: 1,
  },
  {
    oid: 2,
    description: "Chongwe",
    districtCode: "No",
    provinceId: 1,
  },
  {
    oid: 3,
    description: "Kafue",
    districtCode: "No",
    provinceId: 1,
  },
  {
    oid: 4,
    description: "Luangwa",
    districtCode: "No",
    provinceId: 1,
  },
  {
    oid: 5,
    description: "Lusaka",
    districtCode: "5006",
    provinceId: 1,
  },
  {
    oid: 6,
    description: "Rufunsa",
    districtCode: "No",
    provinceId: 1,
  },
  {
    oid: 7,
    description: "Chavuma",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 8,
    description: "Ikelenge",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 9,
    description: "Kabompo",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 10,
    description: "Kalumbila",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 11,
    description: "Kasempa",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 12,
    description: "Manyinga",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 13,
    description: "Mufumbwe",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 14,
    description: "Mushindano",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 15,
    description: "Mwinilunga",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 16,
    description: "Solwezi",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 17,
    description: "Zambezi",
    districtCode: "No",
    provinceId: 2,
  },
  {
    oid: 18,
    description: "Chilubi",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 19,
    description: "Kaputa",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 20,
    description: "Kasama",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 21,
    description: "Lunte",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 22,
    description: "Lupososhi",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 23,
    description: "Luwingu",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 24,
    description: "Mbala",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 25,
    description: "Mporokoso",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 26,
    description: "Mpulungu",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 27,
    description: "Mungwi",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 28,
    description: "Nsama",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 29,
    description: "Senga Hill",
    districtCode: "No",
    provinceId: 3,
  },
  {
    oid: 30,
    description: "Chililabombwe",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 31,
    description: "Chingola",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 32,
    description: "Kalulushi",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 33,
    description: "Kitwe",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 34,
    description: "Luanshya",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 35,
    description: "Lufwanyama",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 36,
    description: "Masaiti",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 37,
    description: "Mpongwe",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 38,
    description: "Mufulira",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 39,
    description: "Ndola",
    districtCode: "No",
    provinceId: 4,
  },
  {
    oid: 40,
    description: "Chinsali",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 41,
    description: "Isoka",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 42,
    description: "Kanchibiya",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 43,
    description: "Lavushi Manda",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 44,
    description: "Mafinga",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 45,
    description: "Mpika",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 46,
    description: "Nakonde",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 47,
    description: "Shiwang'andu",
    districtCode: "No",
    provinceId: 5,
  },
  {
    oid: 48,
    description: "Chikankata",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 49,
    description: "Chirundu",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 50,
    description: "Choma",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 51,
    description: "Gwembe",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 52,
    description: "Itezhi-Tezhi",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 53,
    description: "Kalomo",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 54,
    description: "Kazungula",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 55,
    description: "Livingstone",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 56,
    description: "Mazabuka",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 57,
    description: "Monze",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 58,
    description: "Namwala",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 59,
    description: "Pemba",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 60,
    description: "Siavonga",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 61,
    description: "Sinazongwe",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 62,
    description: "Zimba",
    districtCode: "No",
    provinceId: 6,
  },
  {
    oid: 63,
    description: "Chembe",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 64,
    description: "Chienge",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 65,
    description: "Chifunabuli",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 66,
    description: "Chipili",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 67,
    description: "Kawambwa",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 68,
    description: "Lunga",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 69,
    description: "Mansa",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 70,
    description: "Milenge",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 71,
    description: "Mwansabombwe",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 72,
    description: "Mwense",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 73,
    description: "Nchelenge",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 74,
    description: "Samfya",
    districtCode: "No",
    provinceId: 7,
  },
  {
    oid: 75,
    description: "Chadiza",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 76,
    description: "Chama",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 77,
    description: "Chasefu",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 78,
    description: "Chipangali",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 79,
    description: "Chipata",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 80,
    description: "Kasenengwa",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 81,
    description: "Katete",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 82,
    description: "Lumezi",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 83,
    description: "Lundazi",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 84,
    description: "Lusangazi",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 85,
    description: "Mambwe",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 86,
    description: "Nyimba",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 87,
    description: "Petauke",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 88,
    description: "Sinda",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 89,
    description: "Vubwi",
    districtCode: "No",
    provinceId: 8,
  },
  {
    oid: 90,
    description: "Kalabo",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 91,
    description: "Kaoma",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 92,
    description: "Limulunga",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 93,
    description: "Luampa",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 94,
    description: "Lukulu",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 95,
    description: "Mitete",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 96,
    description: "Mongu",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 97,
    description: "Mulobezi",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 98,
    description: "Mwandi",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 99,
    description: "Nalolo",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 100,
    description: "Nkeyema",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 101,
    description: "Senanga",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 102,
    description: "Sesheke",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 103,
    description: "Shang'ombo",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 104,
    description: "Sikongo",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 105,
    description: "Sioma",
    districtCode: "No",
    provinceId: 9,
  },
  {
    oid: 106,
    description: "Chibombo",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 107,
    description: "Chisamba",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 108,
    description: "Chitambo",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 109,
    description: "Kabwe",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 110,
    description: "Kapiri-Mposhi",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 111,
    description: "Luano",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 112,
    description: "Mkushi",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 113,
    description: "Mumbwa",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 114,
    description: "Ngabwe",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 115,
    description: "Serenje",
    districtCode: "No",
    provinceId: 10,
  },
  {
    oid: 116,
    description: "Shibuyunji",
    districtCode: "No",
    provinceId: 10,
  },
];
