export const medicalEncounterModalTypes = Object.freeze({
  addPresentingComplaint: "addPresentingComplaint",
  editPresentingComplaint: "editPresentingComplaint",
  addTbConstitutionalSymptom: "addTb&ConstitutionalSymptom",
  editTbConstitutionalSymptom: "editTb&ConstitutionalSymptom",
  addReviewOfSystem: "addReviewOfSystem",
  editReviewOfSystem: "editReviewOfSystem",
  addPastMedicalHistory: "addPastMedicalHistory",
  editPastMedicalHistory: "editPastMedicalHistory",
  addChronicNonChronicCondition: "addChronicNonChronicCondition",
  editChronicNonChronicCondition: "editChronicNonChronicCondition",
  addAllergies: "addAllergies",
  editAllergies: "editAllergies",
  addFamilySocial: "addFamilySocial",
  editFamilySocial: "editFamilySocial",
});
